#define IDI_APP_ICON	101

#define IDR_WAYK_BUNDLE		102

#define IDS_WAYK_OPTION_UNATTENDED	103
#define IDS_WAYK_OPTION_DATA_PATH	104
#define IDS_WAYK_OPTION_SYSTEM_PATH	105
#define IDS_WAYK_EXTRACTION_PATH	106
#define IDS_WAYK_PRODUCT_NAME		107
